### ISSUE TITLE
join rackt?

### ISSUE THREAD

**Issue by faassen** [rackt/reselect#51]
While I'm happy to host this on my github page, I don't want to get more credit for this than I should get. What do people think about hosting it under rackt, like Redux?

**Comment by scottcorgan** [comment]
Please do. Putting libraries under this org not only gives it credibility, but ensures it's maintained by more than just a single person.

**Comment by lraivio** [comment]
Reselect is such an integral part of Redux ecosystem, that it would be beneficial to host it under rackt for the reasons listed above.

**Comment by ellbee** [comment]
I really don't mind one way or the other, so I will defer to everyone else on this.

But while you are here @faassen, would you mind having a quick look at #50 :wink:

**Comment by faassen** [comment]
@ellbee I get undeserved credit for this library right now as it's on my github. It's neat people in the community know my name, and I'm happy and proud I helped create this, but I only am one contributor out of a lot of people, some of whom, including you, did more than I did.

**Comment by ellbee** [comment]
Yeah, I appreciate that and I hope that my comment didn't come across as dismissive of the idea. I just wanted to convey that I am totally comfortable with the situation as it is. I do see that there could be benefits to moving the project.

**Comment by SpainTrain** [comment]
I think this is a great idea.  Given the ecosystem's immaturity, it's tough (at least time-consuming) right now to research and choose React technologies.  I'm personally more likely to use a project under the rackt org, and it's nice to save a bit of time on due diligence research (granted, I found reselect through redux docs, so I picked it up with only a skim of the docs).

I agree, as mentioned, that it could also result in more users, more PRs, and lower bus factor.

**Comment by faassen** [comment]
@ellbee No, you did not come across as dismissive at all. I really appreciate your attitude in this towards me a lot!

I contacted Dan Abramov on Twitter and he was in favor of the idea, and he contacted some of the other Rackt people about it. So now we'll see.

**Comment by faassen** [comment]
Note that concerning the bus factor, @ellbee has complete access to everything already. Well, I said that until I learned that there was still a travis thing. Not sure how to give access there.

**Comment by SpainTrain** [comment]
Reasonable.  Bus factor isn't quite the right term.  I think it's more having a slightly larger pool of folks who can spare cycles for reviewing PRs and attending to issues.

Regarding Travis specifically, I _think_ you need owner privilege because you need the "grant privilege' privilege to allow Travis to create web hooks and use build status API.

**Comment by mjackson** [comment]
This sounds like a great idea, and @gaearon [thinks so as well](https://twitter.com/dan_abramov/status/652202754492997632). If you're up for it, our door is open.

**Comment by faassen** [comment]
Okay, back at email I'll initiate the transfer. I wonder whether ellbee's permissions get transferred. We also need to discuss things like npm and travis permissions, but we'll figure it out as we get along.

**Comment by faassen** [comment]
Okay I've transferred the organization to rackt.

We need to figure out whether these things work:

* we enabled some travis stuff recently, and I had to give some permissions for this. Does it work under rackt? 

* ellbee had full access to the reselect repo, and I don't know whether he still does. He really should as he's been the primary maintainer of the project (and initiated the project along with me). I'm not sure whether I have the 

* does rackt have some kind of policy for who has access to the npm for individual projects?

**Comment by gaearon** [comment]
I invited @ellbee to Redux team in rackt.

**Comment by faassen** [comment]
Thanks. But I didn't give any teams (such as redux) access to reselect. I don't think I even have access myself now. :)

**Comment by faassen** [comment]
I do still have commit access. But I don't have access to give people access or give teams access. I'm fine with giving the redux team access to the reselect project though.

**Comment by ellbee** [comment]
Alright, I've joined up! :tada:  And I still have access too, so it's looking good. The travis build badge has broken though.

**Comment by ellbee** [comment]
And fixed.

**Comment by mjackson** [comment]
:D welcome!

**Comment by ellbee** [comment]
Thank you!

**Comment by faassen** [comment]
So any policy for npm?

**Comment by faassen** [comment]
And welcome ellbee! Yay!

**Comment by speedskater** [comment]
@faassen @ellbee sorry for beeing away for a litte long. Great work on reselect and it's really great that redux is rackt now.

**Comment by gaearon** [comment]
Done.
