### ISSUE TITLE
Howto: Use reselect at component-level without connect

### ISSUE THREAD

**Issue by TN1ck** [rackt/reselect#63]
In your docs, it is only mentioned how to use reselect at the `connect`-level, but this wouldn't work with some parts of our application, what we needed was some way to apply functions to the props of the components, and it was actually quite easy to do this with reselect:

I created a function to wrap components with, called select:

```js
let React = require('react');
let _     = require('lodash');

let select = (...selectors) => {
    return (WrappedComponent) => {

        let NewWrappedComponent = React.createClass({
            render: function () {
                let appliedSelectors = selectors.map(fn => {
                    return fn(this.props);
                });
                let calculatedProps = _.merge(...appliedSelectors);
                return <WrappedComponent {...this.props} {...calculatedProps} />;

            }
        });
        return NewWrappedComponent;
    };
};

module.exports = select;

```

With `select` you can easily use selectors at Component-level:

```js
let { createSelector } = require('reselect');
let React = require('react');

let shopItemsSelector = state => state.shop.items
let taxPercentSelector = state => state.shop.taxPercent

const subtotalSelector = createSelector(
  shopItemsSelector,
  items => items.reduce((acc, item) => acc + item.value, 0)
)

let Component = select(subTotalSelector)(React.createClass({...}));

```

I've just build it, so it's really simple at the moment, but it works really good for me, hot-reloading worked out of the box.

I just wanted to share, because someone might have the same use-case as I did.

**Comment by panayi** [comment]
Thanks @TN1ck. I think to be more consistent with `(state, props)` it should be 

```javascript
let appliedSelectors = selectors.map(fn => {
  return fn(_, this.props);
})
```

**Comment by panayi** [comment]
Also here is a version with ES6 classes:

```javascript
import React, { Component } from 'react'
import _ from 'lodash'

const select = (...selectors) => {
  return WrappedComponent => class extends Component {
    render() {
      const appliedSelectors = selectors.map(fn => {
        return fn(_, this.props)
      })
      const calculatedProps = _.merge(...appliedSelectors)
      return (
        <WrappedComponent {...this.props} {...calculatedProps} />
      )
    }
  }
}

export default select
```

**Comment by ellbee** [comment]
@TN1ck @panayi Great, I appreciate both of you writing this up! Thanks.

@panayi Looks like you are passing lodash as the 1st param into the function getting memoized? I guess that was intended to be a placeholder. I'm not sure that I agree about `(_, props)` being more consistent, my initial feeling is that I would leave that function call how @TN1ck had it.

This would be a good fit for [this FAQ question](https://github.com/rackt/reselect#q-can-i-use-reselect-without-redux) on the readme if anyone fancies submitting a pull request. No worries if not, I'll get around to adding it soon.

**Comment by mindjuice** [comment]
@TN1ck Sorry, I'm not following what the purpose of this is.  Do you have a more concrete example and an explanation of why you can't use reselect in the normal way?

Thanks.

**Comment by danny-andrews** [comment]
@TN1ck I don't understand how this code works. Won't `appliedSelectors` just be an array of the results of running the passed-passed in selectors? Something like: `[2, 'cool val', {}]`. So when you run `_.merge(...appliedSelectors)` you're going to get garbage out:
```js
{ [Number: 2]
  '0': 'c',
  '1': 'o',
  '2': 'o',
  '3': 'l',
  '4': ' ',
  '5': 'v',
  '6': 'a',
  '7': 'l' }
```
