### ISSUE TITLE
How-to: use Reselect with props/state

### ISSUE THREAD

**Issue by compulim** [rackt/reselect#64]
Reselect is good for selecting "static" data. But the selection result cannot be always deduced from store alone. Sometimes we could need more information from props or state.

In a master/detail component set, instead of using store, the master could use props to send the ID to the detail component.

It would be great if Reselect could jump in and select data based on store + props.

**Comment by ellbee** [comment]
Sure, check out: https://github.com/rackt/reselect#accessing-react-props-in-selectors
